Fixed an error on the Dockerfile
Following the **Get the files and spin up containers** i got an error saying
```
Step 10/12 : ADD start-container.sh /usr/bin/start-container
ERROR: Service 'app' failed to build: ADD failed: stat /var/lib/docker/tmp/docker-builder283264189/start-container.sh: no such file or directory
```

The script is called `start-container` not `start-container.sh`!
Can fix it by using the actual file name (which doesn't have `.sh` ext)